# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32)),
                ('userId', models.IntegerField(db_index=True)),
                ('signTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sorting',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('villageId', models.IntegerField(default=0)),
                ('streetId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('role', models.IntegerField(default=0)),
                ('createTime', models.IntegerField(default=0)),
            ],
        ),
    ]
