# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentQuestionId', models.IntegerField(db_index=True, default=0)),
                ('info', models.CharField(max_length=1024, null=True)),
                ('imgs', models.CharField(max_length=1024, null=True)),
                ('fraction', models.IntegerField(default=0)),
                ('createTime', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='assessmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oneLevelName', models.CharField(db_index=True, max_length=30)),
                ('shortName', models.CharField(max_length=512)),
                ('info', models.CharField(max_length=1024, null=True)),
                ('fraction', models.IntegerField(default=0)),
                ('answerJson', models.CharField(max_length=1024, null=True)),
                ('subordinateType', models.IntegerField(default=0)),
                ('assessmentType', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetId', models.IntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('personCharge', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('remarks', models.CharField(max_length=1024, null=True)),
                ('managementSubsetNum', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='qrCode',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1024, null=True)),
                ('codeId', models.BigIntegerField(default=0, null=True)),
                ('userId', models.IntegerField(db_index=True, null=True)),
                ('createTime', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='roomNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberText', models.CharField(max_length=1024)),
                ('villageId', models.IntegerField(db_index=True, default=0)),
                ('personCharge', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('remarks', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rsUserVillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(db_index=True)),
                ('rsStreetVillageId', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=32)),
                ('userId', models.IntegerField(db_index=True)),
                ('signTime', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sorting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villageId', models.IntegerField(default=0)),
                ('streetId', models.IntegerField(default=0)),
                ('remarks', models.CharField(max_length=1024, null=True)),
                ('imgs', models.CharField(max_length=1024, null=True)),
                ('qrCodeId', models.UUIDField(null=True)),
                ('createTime', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('personCharge', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('remarks', models.CharField(max_length=1024, null=True)),
                ('managementSubsetNum', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('role', models.IntegerField(default=0)),
                ('createTime', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentId', models.IntegerField(db_index=True, default=0)),
                ('userId', models.IntegerField(db_index=True, default=0)),
                ('streetId', models.IntegerField(db_index=True, default=0)),
                ('community', models.IntegerField(db_index=True, default=0)),
                ('villageId', models.IntegerField(db_index=True, default=0)),
                ('totalFraction', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('createTime', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetId', models.IntegerField(db_index=True, default=0)),
                ('communityId', models.IntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('personCharge', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('remarks', models.CharField(max_length=1024, null=True)),
                ('managementSubsetNum', models.CharField(max_length=100, null=True)),
                ('isOpen', models.IntegerField(default=0)),
            ],
        ),
    ]
