# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftcg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villageId', models.IntegerField(db_index=True, default=0)),
                ('streetId', models.IntegerField(db_index=True, default=0)),
                ('createTime', models.BigIntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('totalIntegral', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='assessmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentId', models.IntegerField(db_index=True, default=0)),
                ('questionId', models.IntegerField(db_index=True, default=0)),
                ('remarks', models.CharField(max_length=2024, null=True)),
                ('imgs', models.CharField(max_length=2024, null=True)),
                ('createTime', models.BigIntegerField(default=0)),
                ('isplusormin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='qrCode',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1024, null=True)),
                ('codeId', models.BigIntegerField(default=0, null=True)),
                ('userId', models.IntegerField(db_index=True, null=True)),
                ('roomNumber', models.IntegerField(db_index=True, null=True)),
                ('createTime', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2024)),
                ('plusFraction', models.IntegerField(default=0)),
                ('minusFraction', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='roomNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberText', models.CharField(max_length=1024)),
                ('villageId', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sorting',
            name='createTime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sorting',
            name='imgs',
            field=models.CharField(max_length=2024, null=True),
        ),
        migrations.AddField(
            model_name='sorting',
            name='qrCodeId',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='sorting',
            name='remarks',
            field=models.CharField(max_length=2024, null=True),
        ),
        migrations.AlterField(
            model_name='sorting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
