# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftcg', '0002_auto_20181210_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
