# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftcg', '0003_auto_20190104_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassessment',
            old_name='community',
            new_name='communityId',
        ),
    ]
