# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftcg', '0003_auto_20181211_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='assessmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subordinateType', models.IntegerField(db_index=True, default=0)),
                ('assessmentType', models.IntegerField(db_index=True, default=0)),
                ('levelJsonString', models.CharField(max_length=20240)),
            ],
        ),
        migrations.RenameField(
            model_name='assessmentquestion',
            old_name='assessmentId',
            new_name='assessmentTypeId',
        ),
        migrations.RenameField(
            model_name='assessmentquestion',
            old_name='questionId',
            new_name='levelOneIndex',
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='levelTwoIndex',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
