# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-06 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftcg', '0004_auto_20190104_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='code',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='codeId',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qrCodeId',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='roomNumberId',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='sorting',
            name='communityId',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='sorting',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sorting',
            name='userId',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='userId',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='rsuservillage',
            name='userId',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sign',
            name='userId',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sorting',
            name='streetId',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sorting',
            name='villageId',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
